### PR TITLE
Add Ace Cloud

### PR DESCRIPTION
**Pull request by nolanfoster123**
Please add Ace Cloud in the list

### CODE REVIEW

**Comment by hcarlens** [comment]
Thanks! We'll review later this week. How long has Ace cloud been around for? How long have you offered GPUs?

**Comment by nolanfoster123** [comment]
> Thanks! We'll review later this week. How long has Ace cloud been around for? How long have you offered GPUs?

The Ace is here since 2006 and the they started offering GPU since last year.

**Comment by gsalberto** [comment]
Please add g3.large.x86 and g3.xlarge.x86 from Latitude.sh to the list
https://www.latitude.sh/pricing

Thanks

**Comment by hcarlens** [comment]
@nolanfoster123 - we show separate prices for 40gb and 80gb A100s now - what are your prices for those?

**Comment by gsalberto** [comment]
Harald,

We don't have A100s, we are only providing H100 GPUs

Prices attached

Thanks

*Guilherme Soubihe* , CEO

**Comment by nolanfoster123** [comment]
@hcarlens The pricing for Nvidia A100 40GB is $1.50/hr and Nvidia A100 80GB is $3/hr.

**Comment by hcarlens** [comment]
Thanks @nolanfoster123! ACE Cloud has now been added, I did it in a separate commit since the data spec has changed slightly: https://github.com/cloud-gpus/cloud-gpus.github.io/commit/54f8d1a445d4c0a0b7c10b1ae62a9a141ba60c11

**Pull request closed without merging**
