### PR TITLE
Added Cerebrium cloud prices

### PR DESCRIPTION
**Pull request by milo157**

### CODE REVIEW

**Comment by hcarlens** [comment]
Thanks, and sorry for the delay - I'll try to review this shortly.

**Comment by hcarlens** [comment]
Hi @milo157, sorry again for the delay here. Could you tell me a bit more about how Cerebrium works? 
I'm mainly trying to figure out: does Cerebrium have its own hardware, or does it run on hardware in other providers' data centres? (if so, is the list of providers public?)

**Comment by milo157** [comment]
@hcarlens We do not have our own hardware but currently run on Coreweave and AWS - adding more cloud providers in the future. This allows engineers to easily switch between cloud providers based on cost, availability of GPUs etc without having to worry about the infra setup. Also because we run workflows serverlessly (spinning instances up, executing workloading, spinning down again) our users save significant costs

**Comment by hcarlens** [comment]
Thanks! We're planning to add a page listing providers like yours in the future. I'll close this for now. 

I think more abstraction on top of VMs is helpful, but at the moment this page just lists GPUs that can be attached to VMs.

**Pull request closed without merging**
